# Generated by Django 4.2.19 on 2025-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='spot',
            unique_together={('parking_spot', 'spot_number')},
        ),
    ]
