# Generated by Django 4.2.19 on 2025-03-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reminder_sent',
        ),
    ]
