# Generated by Django 4.2.19 on 2025-03-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]