# Generated by Django 4.2.19 on 2025-03-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_booking_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
